clear all;
AGE=10;YEAR=2025;

for AGE = [10]%[10 12 14]

    fprintf('Starting %d %d\n',AGE,YEAR);
    AGE_MIN=AGE-2;AGE_MAX=AGE+2;

    STATS_FILE=sprintf('player_stats_%d_%d.csv',AGE,YEAR);
    NAMES_FILE=sprintf('player_names_%d_%d.csv',AGE,YEAR);
    FULL_FILE=sprintf('full_stats_%d_%d.csv',AGE,YEAR);

    fid1=fopen(STATS_FILE,'w');
    fid2=fopen(NAMES_FILE,'w');

    pl_list={   'NU' };


    switch YEAR
        case 2024
            switch AGE
                case 10
                    tm_list={   'CapitalThunder,10A', ...
                                'CupertinoCougars,10A', ...
                                'CupertinoCougars,10BB', ...
                                'FresnoJrMonsters,10BB', ...
                                'LakeTahoeGrizzlies,10B', ...
                                'OaklandBears,10B', ...
                                'RenoIce,10A', ...
                                'SanFranciscoSabercats,10A', ...
                                'SanFranciscoSabercats,10B', ...
                                'SanJoseJrSharks,10A-1', ...
                                'SanJoseJrSharks,10A-2', ...
                                'SanJoseJrSharks,10A-3', ...
                                'SanJoseJrSharks,10B-1', ...
                                'SanJoseJrSharks,10B-2', ...
                                'SanJoseJrSharksGirls,10X', ...
                                'SanMateoBlackStars,10BB', ...
                                'SantaClaraBlackhawks,10A', ...
                                'SantaClaraBlackhawks,10B', ...
                                'SantaRosaFlyers,10B', ...
                                'SantaRosaFlyers,10BB', ...
                                'StocktonColts,10A', ...
                                'StocktonColtsGirls,10B', ...
                                'TriValleyBlueDevils,10A-1', ...
                                'TriValleyBlueDevils,10A-2', ...
                                'TriValleyBlueDevils,10B', ...
                                'TriValleyBlueDevils,10BB', ...
                                'TriValleyBlueDevils,10X2', ...
                                'TriValleyLadyBlueDevils,10B', ...
                                'VacavilleJets,10B', ...
                                'VacavilleJets,10BB'};
                case 12
                    tm_list={   'TriValleyBlueDevils,12A-2', ...
                                'StocktonColts,12A', ...
                                'SanJoseJrSharks,12A-1', ...
                                'VacavilleJets,12A', ...
                                'RenoIce,12A', ...
                                'SanFranciscoSabercats,12A', ...
                                'SanMateoBlackstars,12A', ...
                                'CapitalThunder,12A', ...
                                'SanJoseJrSharks,12A-2', ...
                                'SantaClaraBlackhawks,12A', ...
                                'CupertinoCougars,12A', ...
                                'TriValleyBlueDevils,12A-1', ...
                                'SanJoseJrSharks,12AA-1', ...
                                'OaklandBears,12AA', ...
                                'SanJoseJrSharks,12AA-3', ...
                                'GoldenStateElite,12AA-1', ...
                                'SanJoseJrSharks,12AA-2', ...
                                'LakeTahoeGrizzlies,12B', ...
                                'RenoIce,12B', ...
                                'VacavilleJets,12B', ...
                                'OaklandBears,12B', ...
                                'SanMateoBlackStars,12B', ...
                                'TriValleyBlueDevils,12B', ...
                                'SanFranciscoSabercats,12B', ...
                                'SantaRosaFlyers,12B', ...
                                'StocktonColtsGirls,12B', ...
                                'SantaRosaFlyers,12BB', ...
                                'TriValleyBlueDevils,12BB', ...
                                'CupertinoCougars,12BB', ...
                                'FresnoJrMonsters,12BB', ...
                                'SantaClaraBlackhawks,12BB'};
                case 14
                    tm_list={   'CapitalThunder,14A', ...
                                'CapitalThunder,14B', ...
                                'CupertinoCougars,14A', ...
                                'CupertinoCougars,14B', ...
                                'FresnoJrMonsters,14B', ...
                                'OaklandBears,14B', ...
                                'RenoIce,14A', ...
                                'RenoIce,14B', ...
                                'SanFranciscoSabercats,14A', ...
                                'SanFranciscoSabercats,14B', ...
                                'SanJoseJrSharks,14A', ...
                                'SanJoseJrSharks,14B', ...
                                'SanMateoBlackStars,14B', ...
                                'SantaClaraBlackhawks,14B', ...
                                'SantaRosaFlyers,14A', ...
                                'SantaRosaFlyers,14B', ...
                                'StocktonColts,14A', ...
                                'TriValleyBlueDevils,14A', ...
                                'TriValleyBlueDevils,14B-1', ...
                                'TriValleyBlueDevils,14B-2', ...
                                'VacavilleJets,14A', ...
                                'VacavilleJets,14B'};
            end;
        case 2025
            switch AGE
                case 10
                    tm_list={   'CapitalThunder,10', ...
                                'CupertinoCougars,10-1', ...
                                'CupertinoCougars,10-2', ...
                                'FresnoJrMonsters,10', ...
                                'LakeTahoeGrizzlies,10-1', ...
                                'LakeTahoeGrizzlies,10-2', ...
                                'OaklandBears,10-1', ...
                                'OaklandBears,10-2', ...
                                'RenoIce,10A', ...
                                'SanFranciscoSabercats,10-1', ...
                                'SanFranciscoSabercats,10-2', ...
                                'SanJoseJrSharks,10-1', ...
                                'SanJoseJrSharks,10-2', ...
                                'SanJoseJrSharks,10-3', ...
                                'SanJoseJrSharks,10-4', ...
                                'SanJoseJrSharks,10-5', ...
                                'SanJoseJrSharksGirls,10', ...
                                'SanMateoBlackStars,10', ...
                                'SantaClaraBlackhawks,10-1', ...
                                'SantaClaraBlackhawks,10-2', ...
                                'SantaRosaFlyers,10-1', ...
                                'SantaRosaFlyers,10-2', ...
                                'StocktonColts,10', ...
                                'StocktonColtsGirls,10B', ...
                                'TriValleyBlueDevils,10-1', ...
                                'TriValleyBlueDevils,10-2', ...
                                'TriValleyBlueDevils,10-3', ...
                                'TriValleyLadyBlueDevils,10', ...
                                'VacavilleJets,10-1', ...
                                'VacavilleJets,10-2'};
                case 12
                    tm_list={   'TriValleyBlueDevils,12A-2', ...
                                'StocktonColts,12A', ...
                                'SanJoseJrSharks,12A-1', ...
                                'VacavilleJets,12A', ...
                                'RenoIce,12A', ...
                                'SanFranciscoSabercats,12A', ...
                                'SanMateoBlackstars,12A', ...
                                'CapitalThunder,12A', ...
                                'SanJoseJrSharks,12A-2', ...
                                'SantaClaraBlackhawks,12A', ...
                                'CupertinoCougars,12A', ...
                                'TriValleyBlueDevils,12A-1', ...
                                'SanJoseJrSharks,12AA-1', ...
                                'OaklandBears,12AA', ...
                                'SanJoseJrSharks,12AA-3', ...
                                'GoldenStateElite,12AA-1', ...
                                'SanJoseJrSharks,12AA-2', ...
                                'LakeTahoeGrizzlies,12B', ...
                                'RenoIce,12B', ...
                                'VacavilleJets,12B', ...
                                'OaklandBears,12B', ...
                                'SanMateoBlackStars,12B', ...
                                'TriValleyBlueDevils,12B', ...
                                'SanFranciscoSabercats,12B', ...
                                'SantaRosaFlyers,12B', ...
                                'StocktonColtsGirls,12B', ...
                                'SantaRosaFlyers,12BB', ...
                                'TriValleyBlueDevils,12BB', ...
                                'CupertinoCougars,12BB', ...
                                'FresnoJrMonsters,12BB', ...
                                'SantaClaraBlackhawks,12BB'};
                case 14
                    tm_list={   'CapitalThunder,14A', ...
                                'CapitalThunder,14B', ...
                                'CupertinoCougars,14A', ...
                                'CupertinoCougars,14B', ...
                                'FresnoJrMonsters,14B', ...
                                'OaklandBears,14B', ...
                                'RenoIce,14A', ...
                                'RenoIce,14B', ...
                                'SanFranciscoSabercats,14A', ...
                                'SanFranciscoSabercats,14B', ...
                                'SanJoseJrSharks,14A', ...
                                'SanJoseJrSharks,14B', ...
                                'SanMateoBlackStars,14B', ...
                                'SantaClaraBlackhawks,14B', ...
                                'SantaRosaFlyers,14A', ...
                                'SantaRosaFlyers,14B', ...
                                'StocktonColts,14A', ...
                                'TriValleyBlueDevils,14A', ...
                                'TriValleyBlueDevils,14B-1', ...
                                'TriValleyBlueDevils,14B-2', ...
                                'VacavilleJets,14A', ...
                                'VacavilleJets,14B'};
            end;
    end;

    a=[1 2 3 4 5 6 7 8];
    a=[1];
% season = 31
    for t=1:length(a)
        switch t
            case 1
                x=urlread('https://stats.caha.timetoscore.com/display-schedule?season=31&league=3&stat_class=1'); 
            case 2
                x=urlread('https://stats.caha.timetoscore.com/display-schedule.php?stat_class=5&league=18&season=31');
            case 3
                x=urlread('https://stats.caha.timetoscore.com/display-schedule.php?stat_class=5&league=35&season=31');
            case 4
                x=urlread('https://stats.caha.timetoscore.com/display-schedule.php?stat_class=5&league=39&season=31');
            case 5
                x=urlread('https://stats.caha.timetoscore.com/display-schedule.php?stat_class=5&league=13&season=31');
            case 6
                x=urlread('https://stats.caha.timetoscore.com/display-schedule.php?stat_class=5&league=24&season=31');
            case 7
                x=urlread('https://stats.cna.timetoscore.com//display-schedule.php?league=48&season=38');
            case 8
                x=urlread('https://stats.asec.timetoscore.com/display-schedule.php?stat_class=1&league=14&season=27');
                fid=fopen(sprintf('games/asec_14_27.html'),'r');
                x=fscanf(fid,'%s');
                                                (fid);
        end;

        x=regexprep(x,'<b>','');x=regexprep(x,'</b>','');
        [u1,u2]=regexp(x,'oss[-]+scoresheet[?]+game[_]+id[=]+[0-9]+[&]+mode[=]+display">[0-9]*[*]+</a>[\s]*</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>');

        for v=1:length(u1)
            tmp0=x(u1(v):u2(v));
            tmp1=regexprep(tmp0,'oss[-]+scoresheet[?]+game[_]+id[=]+([0-9]+)[&]+mode[=]+display">[0-9]*[*]+</a>[\s]*</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>([^<]+)</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>','$1');
            age1=regexprep(tmp0,'oss[-]+scoresheet[?]+game[_]+id[=]+([0-9]+)[&]+mode[=]+display">[0-9]*[*]+</a>[\s]*</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>[^<]+</td>[\s]*<td>([^<]+)</td>[\s]*<td>([^<]+)</td>[\s]*<td>[^<]+</td>[\s]*<td>([^<]+)</td>','$2,$3,$4');

            if ~isempty(regexp(age1,num2str(AGE)))

                if t<7
                    dl_url=strcat('https://stats.caha.timetoscore.com/oss-scoresheet?game_id=',tmp1,'&mode=display');
                else
                    if t==7
                        dl_url=strcat('https://stats.cna.timetoscore.com/oss-scoresheet?game_id=',tmp1,'&mode=display');
                    else
                        dl_url=strcat('https://stats.asec.timetoscore.com/oss-scoresheet?game_id=',tmp1,'&mode=display');
                        tmp2=strcat(tmp1,'0');
                    end;
                end;
                
                try
                    if t<=6
                        fid=fopen(sprintf('games/%s.html',tmp1),'r');
                    else
                        fid=fopen(sprintf('games/%s.html',tmp2),'r');
                    end;
                    y=fscanf(fid,'%s');
                    fclose(fid);
                    %fprintf('Found %s\n',tmp1); % prints out
                catch
                    if t<=7
                        urlwrite(dl_url,sprintf('games/%s.html',tmp1));
                        fprintf('New %s\n',tmp1); % prints out
                    else
                        urlwrite(dl_url,sprintf('games/%s.html',tmp2));
                        fprintf('New %s\n',tmp2); % prints out
                    end;
                    pause(5+rand(1)*5);
                    if t<=7
                        fid=fopen(sprintf('games/%s.html',tmp1),'r');
                        y=fscanf(fid,'%s');
                        fclose(fid);
                        fprintf('Found %s\n',tmp1); % prints out
                    else
                        fid=fopen(sprintf('games/%s.html',tmp2),'r');
                        y=fscanf(fid,'%s');
                        fclose(fid);
                        fprintf('Found %s\n',tmp2); % prints out
                    end;
                end;
                
                if strmatch('20929',tmp1)
                    sprintf('20929\n');
                end;

                [s1,s2]=regexp(y,'[A-Za-z\s]+[\s]*[(]*[A-Z0-9-]+[)]*[\s]*Players[\s]*in[\s]*[Gg]+ame[\s]*[0-9]+');
                awtm=regexprep(y(s1(1):s2(1)),'([A-Za-z\s]+)[\s]*[(]*([A-Z0-9-]+)[)]*[\s]*Players[\s]*in[\s]*[Gg]+ame[\s]*[0-9]+','$1,$2');
                hmtm=regexprep(y(s1(2):s2(2)),'([A-Za-z\s]+)[\s]*[(]*([A-Z0-9-]+)[)]*[\s]*Players[\s]*in[\s]*[Gg]+ame[\s]*[0-9]+','$1,$2');
                awtm=regexprep(awtm,'10X2','10B');
                hmtm=regexprep(hmtm,'10X2','10B');
                awtm=regexprep(awtm,'10X','10B');
                hmtm=regexprep(hmtm,'10X','10B');
                awtm=regexprep(awtm,'10U','10');
                hmtm=regexprep(hmtm,'10U','10');
                awtm=regexprep(awtm,'12U','12');
                hmtm=regexprep(hmtm,'12U','12');
                awtm=regexprep(awtm,'14U','14');
                hmtm=regexprep(hmtm,'14U','14');
                [t1,t2]=regexp(y,'Scoring');
                [r1,r2]=regexp(y,'</table>');

                awrs=y(s1(1):r1(min(find(r1>s1(1)))));
                hmrs=y(s1(2):r1(min(find(r1>s1(2)))));

                [ap1,ap2]=regexp(awrs,'<TD[\s]*align[=]+center>[^<]*</td>[\s]*<TD[\s]*align=center>[^<]*</td>[\s]*<TD[\s]*align=center>[^<]+</td>');
                [hp1,hp2]=regexp(hmrs,'<TD[\s]*align[=]+center>[^<]*</td>[\s]*<TD[\s]*align=center>[^<]*</td>[\s]*<TD[\s]*align=center>[^<]+</td>');

                for z=1:length(ap1)
                    apnu=regexprep(awrs(ap1(z):ap2(z)),'<TD[\s]*align[=]+center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]+)</td>','$1');
                    apna=regexprep(awrs(ap1(z):ap2(z)),'<TD[\s]*align[=]+center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]+)</td>','$3');apna=regexprep(apna,'[(]+[*]+[0-9]+[)]+','');
                    appo=regexprep(awrs(ap1(z):ap2(z)),'<TD[\s]*align[=]+center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]+)</td>','$2');
                    appo=regexprep(appo,'[&]+nbsp[;]+','');
                    tmnm=find(strcmp(tm_list, awtm));
                    gl=isempty(strfind(appo,"G"));
                    if and(and(isempty(strfind(apnu,"C")),and(isempty(strfind(awtm,num2str(AGE_MIN))),isempty(strfind(awtm,num2str(AGE_MAX))))),~isempty(tmnm))
                        plnm=find(strcmp(pl_list,apna));
                        if isempty(plnm)
                            pl_list=[pl_list, apna ];
                            plnm=find(strcmp(pl_list,apna));
                        end;
                        fprintf(fid2,'%s,%s,%s,%d,%s,%s,%d,%d\n',awtm,apna,appo,tmnm,tmp1,apnu,plnm,gl);
                    end;
                end;
                for z=1:length(hp1)
                    hpnu=regexprep(hmrs(hp1(z):hp2(z)),'<TD[\s]*align[=]+center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]+)</td>','$1');
                    hpna=regexprep(hmrs(hp1(z):hp2(z)),'<TD[\s]*align[=]+center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]+)</td>','$3');hpna=regexprep(hpna,'[(]+[*]+[0-9]+[)]+','');
                    hppo=regexprep(hmrs(hp1(z):hp2(z)),'<TD[\s]*align[=]+center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]*)</td>[\s]*<TD[\s]*align=center>([^<]+)</td>','$2');
                    hppo=regexprep(hppo,'[&]+nbsp[;]+','');
                    tmnm=find(strcmp(tm_list, hmtm));
                    gl=isempty(strfind(hppo,"G"));
                    if and(and(isempty(strfind(hpnu,"C")),and(isempty(strfind(hmtm,num2str(AGE_MIN))),isempty(strfind(hmtm,num2str(AGE_MAX))))),~isempty(tmnm))
                        plnm=find(strcmp(pl_list,hpna));
                        if isempty(plnm)
                            pl_list=[ pl_list, hpna ];
                            plnm=find(strcmp(pl_list,hpna));
                        end;
                        fprintf(fid2,'%s,%s,%s,%d,%s,%s,%d,%d\n',hmtm,hpna,hppo,tmnm,tmp1,hpnu,plnm,gl);
                    end;
                end;


                awsc=y(t1(1):r1(min(find(r1>t1(1)))));
                hmsc=y(t1(2):r1(min(find(r1>t1(2)))));

                srch_str='<tr[\s]*bgcolor="[^"]+">[\s]*<TD[^>]+>[^<]+</td>[\s]*<TD[^>]+>[^<]+</td>[\s]*<TD[^>]+>[^<]+</td>[\s]*<TD[^>]+>[^<]+</td>[\s]*<TD[^>]+>[^<]+</td>[\s]*<TD[^>]+>[^<]+</td>';
                repl_str='<tr[\s]*bgcolor="[^"]+">[\s]*<TD[^>]+>[^<]+</td>[\s]*<TD[^>]+>[^<]+</td>[\s]*<TD[^>]+>[^<]+</td>[\s]*<TD[^>]+>([^<]+)</td>[\s]*<TD[^>]+>([^<]+)</td>[\s]*<TD[^>]+>([^<]+)</td>';

                [a1,a2]=regexp(awsc,srch_str);                
                [h1,h2]=regexp(hmsc,srch_str);                

                for z=1:length(a1)
                    tmpaw=awsc(a1(z):a2(z));
                    awgl=regexprep(tmpaw,repl_str,'$1');awgl=regexprep(awgl,'[&]+nbsp[;]+','');
                    awa1=regexprep(tmpaw,repl_str,'$2');awa1=regexprep(awa1,'[&]+nbsp[;]+','');
                    awa2=regexprep(tmpaw,repl_str,'$3');awa2=regexprep(awa2,'[&]+nbsp[;]+','');
                    tmnm=find(strcmp(tm_list, awtm));
                    if and(and(isempty(strfind(awtm,num2str(AGE_MIN))),isempty(strfind(awtm,num2str(AGE_MAX)))),~isempty(tmnm))
                        fprintf(fid1,'%s,%s,%s,%s,%s,%d\n',awtm,tmp1,awgl,awa1,awa2,tmnm);
                    end;
                end;
                for z=1:length(h1)
                    tmphm=hmsc(h1(z):h2(z));
                    hmgl=regexprep(tmphm,repl_str,'$1');hmgl=regexprep(hmgl,'[&]+nbsp[;]+','');
                    hma1=regexprep(tmphm,repl_str,'$2');hma1=regexprep(hma1,'[&]+nbsp[;]+','');
                    hma2=regexprep(tmphm,repl_str,'$3');hma2=regexprep(hma2,'[&]+nbsp[;]+','');
                    tmnm=find(strcmp(tm_list, hmtm));
                    if and(and(isempty(strfind(hmtm,num2str(AGE_MIN))),isempty(strfind(hmtm,num2str(AGE_MAX)))),~isempty(tmnm))
                        fprintf(fid1,'%s,%s,%s,%s,%s,%d\n',hmtm,tmp1,hmgl,hma1,hma2,tmnm);
                    end;
                end;

            end;

        end;
    end;
    fclose('all');

    gstats=csvread(STATS_FILE,0,2);
    pstats=csvread(NAMES_FILE,0,4);

    gp=zeros(length(pl_list),length(tm_list));
    gg=gp;
    goals=gp;assts=gp;

    for t=1:length(pstats(:,1))
        if pstats(t,5)==1
            gp(pstats(t,4),pstats(t,1))=gp(pstats(t,4),pstats(t,1))+1;
        else
            gg(pstats(t,4),pstats(t,1))=gg(pstats(t,4),pstats(t,1))+1;
        end;
    end;

    for t=1:length(gstats(:,1))
        g1=gstats(t,1);
        t1=gstats(t,5);
        p1=gstats(t,2);
        p2=gstats(t,3);
        p3=gstats(t,4);

        if p1>0
            tmpx=pstats(find(and(pstats(:,2)==g1,and(pstats(:,1)==t1,pstats(:,3)==p1))),:);
            pnum=tmpx(1,4);
            goals(pnum,t1)=goals(pnum,t1)+length(tmpx(:,1));
        end;
        if p2>0
            tmpx=pstats(find(and(pstats(:,2)==g1,and(pstats(:,1)==t1,pstats(:,3)==p2))),:);
            pnum=tmpx(1,4);
            assts(pnum,t1)=assts(pnum,t1)+length(tmpx(:,1));
        end;
        if p3>0
            tmpx=pstats(find(and(pstats(:,2)==g1,and(pstats(:,1)==t1,pstats(:,3)==p3))),:);
            pnum=tmpx(1,4);
            assts(pnum,t1)=assts(pnum,t1)+length(tmpx(:,1));
        end;

    end;

    fid3=fopen(FULL_FILE,'w');
    fprintf(fid3,'Name,Team,Level,GP,G,A,P,GP Goaltender\n');
    for t=2:length(pl_list)
        for u=1:length(tm_list)
            if or(gp(t,u)>0,gg(t,u)>0)
                fprintf(fid3,'%s,%s,%d,%d,%d,%d,%d\n', pl_list{t},tm_list{u},gp(t,u),goals(t,u),assts(t,u),goals(t,u)+assts(t,u),gg(t,u));
            end;
        end;
    end;
    fclose('all');
end;